CREATE TABLE IF NOT EXISTS plant (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NAME VARCHAR(255),
    ORIGIN VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    SEASON_FOUND VARCHAR(255),
    IMAGE_URL VARCHAR(255),
    CONSTRAINT PK_PLANT PRIMARY KEY (ID)
    );

INSERT INTO plant (name, origin, description, season_found, image_url) VALUES
                                                                           ('Aloe Vera', 'Afrique du Nord', 'Plante médicinale connue pour ses propriétés cicatrisantes et hydratantes.', 'Été', 'https://example.com/images/aloe-vera.jpg'),
                                                                           ('Camomille', 'Europe', 'Utilisée pour ses effets calmants et digestifs, souvent en infusion.', 'Printemps', 'https://example.com/images/camomille.jpg'),
                                                                           ('Menthe poivrée', 'Méditerranée', 'Plante aromatique aux vertus digestives et rafraîchissantes.', 'Été', 'https://example.com/images/menthe.jpg'),
                                                                           ('Gingembre', 'Asie du Sud', 'Racine stimulante utilisée contre les nausées et pour renforcer l’immunité.', 'Hiver', 'https://example.com/images/gingembre.jpg'),
                                                                           ('Thym', 'Europe du Sud', 'Antiseptique naturel utilisé contre les infections respiratoires.', 'Automne', 'https://example.com/images/thym.jpg'),
                                                                           ('Lavande', 'Provence', 'Plante relaxante utilisée en aromathérapie et pour apaiser les douleurs.', 'Été', 'https://example.com/images/lavande.jpg'),
                                                                           ('Eucalyptus', 'Australie', 'Plante expectorante utilisée pour dégager les voies respiratoires.', 'Hiver', 'https://example.com/images/eucalyptus.jpg'),
                                                                           ('Romarin', 'Bassin méditerranéen', 'Stimulant circulatoire et tonique digestif.', 'Printemps', 'https://example.com/images/romarin.jpg');