
CREATE TABLE plant
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    origin       VARCHAR(255),
    description  VARCHAR(255),
    season_found VARCHAR(255),
    image_url    VARCHAR(255),
    CONSTRAINT pk_plant PRIMARY KEY (id)
);

